import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const scene=new THREE.Scene();scene.background=new THREE.Color(0x75aadb);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,200);camera.position.set(0,13,18);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x355c35,2));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(10,25,10);sun.castShadow=true;scene.add(sun);
const field=new THREE.Mesh(new THREE.PlaneGeometry(42,68),new THREE.MeshStandardMaterial({color:0x23823b}));field.rotation.x=-Math.PI/2;scene.add(field);
const lm=new THREE.MeshBasicMaterial({color:0xffffff});function line(x,z,w,d){let m=new THREE.Mesh(new THREE.PlaneGeometry(w,d),lm);m.rotation.x=-Math.PI/2;m.position.set(x,.02,z);scene.add(m)}line(0,-34,42,.15);line(0,34,42,.15);line(-21,0,.15,68);line(21,0,.15,68);line(0,0,42,.12);let c=new THREE.Mesh(new THREE.RingGeometry(6,6.12,64),lm);c.rotation.x=-Math.PI/2;c.position.y=.02;scene.add(c);
function player(color,x,z){let g=new THREE.Group();let b=new THREE.Mesh(new THREE.CylinderGeometry(.42,.5,1.1,10),new THREE.MeshStandardMaterial({color}));b.position.y=.75;b.castShadow=true;g.add(b);let h=new THREE.Mesh(new THREE.SphereGeometry(.3,10,8),new THREE.MeshStandardMaterial({color:0x8b5a3c}));h.position.y=1.55;g.add(h);g.position.set(x,0,z);scene.add(g);return g}
const user=player(0x1769aa,0,18);const mates=[[-8,10],[8,10],[-10,-2],[10,-2]].map(p=>player(0x1769aa,...p));const opponents=[[-6,-12],[6,-12],[-10,-3],[10,-3],[0,-22]].map(p=>player(0xd62d3b,...p));
const ball=new THREE.Mesh(new THREE.SphereGeometry(.3,16,12),new THREE.MeshStandardMaterial({color:0xffffff}));ball.position.set(0,.3,15);scene.add(ball);ball.userData.vel=new THREE.Vector3();
const keys={};addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);const bind=(id,key)=>{let b=document.getElementById(id);b.onpointerdown=e=>{e.preventDefault();keys[key]=true};b.onpointerup=()=>keys[key]=false;b.onpointerleave=()=>keys[key]=false};bind('up','w');bind('down','s');bind('left','a');bind('right','d');
function kick(power){ball.userData.vel.set(0,0,-power);document.getElementById('status').textContent=power>5?'SHOOT!':'PASS!'}document.getElementById('pass').onclick=()=>kick(3);document.getElementById('shoot').onclick=()=>kick(8);
let last=performance.now();function loop(now){requestAnimationFrame(loop);let dt=Math.min((now-last)/1000,.033);last=now;let dx=(keys.d?1:0)-(keys.a?1:0),dz=(keys.s?1:0)-(keys.w?1:0),l=Math.hypot(dx,dz)||1;user.position.x=Math.max(-19,Math.min(19,user.position.x+dx/l*7*dt));user.position.z=Math.max(-32,Math.min(32,user.position.z+dz/l*7*dt));ball.position.addScaledVector(ball.userData.vel,dt);ball.userData.vel.multiplyScalar(Math.pow(.08,dt));opponents.forEach(p=>p.position.lerp(new THREE.Vector3(ball.position.x,0,ball.position.z),.004));camera.position.lerp(new THREE.Vector3(user.position.x,12,user.position.z+15),.08);camera.lookAt(user.position.x,0,user.position.z-8);renderer.render(scene,camera)}requestAnimationFrame(loop);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});